### ISSUE TITLE
Implementation for IGameServersService - GetAccountPublicInfo

### ISSUE THREAD

**Issue by Aquerr** [Aquerr/steam-web-api-client#45]
This endpoint seems to be returning the steamid of GSLT itself + the app id.

Request:
|Parameter|Type|Description|
|----------|-----|-----------|
|key|string| The API KEY|
|steamid|uint64|The steam id of the GSLT|

Response:
|Parameter|Type|Description|
|----------|-----|-----------|
|steamid|uint64|The steam id of the GSLT|
|appid|uint32|The id of the app that the corresponding GSLT is for|

**Comment by jayceslesar** [comment]
as far as I know this endpoint just returns nothing? Super weird unsure how you would fix in this lib seems like steam might have changed that and not documented it

**Comment by Aquerr** [comment]
@jayceslesar Not sure yet, haven't looked at this since few months. 
If it is like you are saying, then probably there is no point implementing it.
